// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWYqugkeL0L-GQpYoY72he36P-Y1FmPRo',
    appId: '1:75707891733:web:9dcdf8a024f2cf3b9f4e1c',
    messagingSenderId: '75707891733',
    projectId: 'track-4cfbe',
    authDomain: 'track-4cfbe.firebaseapp.com',
    storageBucket: 'track-4cfbe.appspot.com',
    measurementId: 'G-CNH09BHWCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ36H4yU9MrwDNK06TRvrmn3BE-gP5I-Q',
    appId: '1:75707891733:android:39bba9c4596863b09f4e1c',
    messagingSenderId: '75707891733',
    projectId: 'track-4cfbe',
    storageBucket: 'track-4cfbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG8gNmrtUY_sl_zP_1tkaPgMEcqobPWRM',
    appId: '1:75707891733:ios:dddfa78bf487af849f4e1c',
    messagingSenderId: '75707891733',
    projectId: 'track-4cfbe',
    storageBucket: 'track-4cfbe.appspot.com',
    iosBundleId: 'com.example.tracksystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG8gNmrtUY_sl_zP_1tkaPgMEcqobPWRM',
    appId: '1:75707891733:ios:dddfa78bf487af849f4e1c',
    messagingSenderId: '75707891733',
    projectId: 'track-4cfbe',
    storageBucket: 'track-4cfbe.appspot.com',
    iosBundleId: 'com.example.tracksystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWYqugkeL0L-GQpYoY72he36P-Y1FmPRo',
    appId: '1:75707891733:web:0a7e53e2e7e396ae9f4e1c',
    messagingSenderId: '75707891733',
    projectId: 'track-4cfbe',
    authDomain: 'track-4cfbe.firebaseapp.com',
    storageBucket: 'track-4cfbe.appspot.com',
    measurementId: 'G-H10NL4XT51',
  );
}
